/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffd9dd",
        "on-surface-variant": "#544244",
        "primary": "#6e2334",
        "tertiary-fixed-dim": "#d0c5ba",
        "tertiary-fixed": "#ede0d5",
        "surface-container-highest": "#e9e0e0",
        "primary-fixed-dim": "#ffb2bc",
        "on-secondary-fixed": "#281800",
        "tertiary-container": "#5b534b",
        "surface-bright": "#fff8f7",
        "outline": "#877274",
        "inverse-on-surface": "#f8efee",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#604100",
        "surface-container-high": "#efe6e6",
        "secondary-fixed-dim": "#efbf73",
        "on-tertiary-fixed": "#201b14",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#400013",
        "secondary-fixed": "#ffdeae",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-surface": "#1e1b1b",
        "inverse-primary": "#ffb2bc",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#792c3c",
        "primary-container": "#8b3a4a",
        "background": "#fff8f7",
        "on-tertiary-fixed-variant": "#4d463e",
        "on-background": "#1e1b1b",
        "inverse-surface": "#342f2f",
        "tertiary": "#433c34",
        "on-secondary": "#ffffff",
        "surface-tint": "#974353",
        "on-primary-container": "#ffb7c0",
        "on-tertiary-container": "#d3c7bd",
        "surface-container": "#f5eceb",
        "surface-container-low": "#fbf2f1",
        "secondary": "#7c5816",
        "outline-variant": "#d9c1c3",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#795513",
        "on-error": "#ffffff",
        "surface-variant": "#e9e0e0",
        "surface": "#fff8f7",
        "surface-dim": "#e1d8d8",
        "secondary-container": "#fecc80"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "margin-mobile": "1.25rem",
        "margin-tablet": "2.5rem",
        "margin-desktop": "4rem",
        "gutter-mobile": "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2rem"
      },
      fontFamily: {
        "display": ["Playfair Display", "serif"],
        "display-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["30px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
